steps:
- id: 'Initial'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
    - '-c'
    - echo "This is initial step"


options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

