steps:
- id: 'Initial'
  entrypoint: 'sh'
  args:
    - '-c'
    - echo "This is initial step"

- id: 'middle'
  entrypoint: 'sh'
  args:
  - '-c'
  - echo "This is middle step"

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

